spring:
  application:
    name: terminal-server
     
 

eureka:
  instance:
    appname: terminal-server 
  client:   
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
    
server:
  port: 8000  